site_name: ROAR
site_description: Robot Autonomous Racing DeCal is a course dedicated to teaching students to gain a holistic view and hands-on(virtual) experiences about building a high-performance fully-autonomous 1/10 scale RC car from scratch.
site_url: https://roar-decal.github.io/Carla/
theme:
  name: material

nav:
  - Home: index.md
  - Setup: Gettingstarted/startcarla.md
  - Overview of Project Layout: layout/projectlayout.md
  - Lectures:
    - Arduino/Jetson Nano: lectures_folder/A&JN.md
    - Computer Vision: lectures_folder/CV.md
    - PID Control: lectures_folder/PID.md
    - 3D Printing: lectures_folder/3DPrint.md


plugins:
  - search
  - mkdocstrings
